const passport = require('passport');
const mongoose = require('mongoose');
const GoogleStrategy = require('passport-google-oauth20').Strategy;

const keys = require('../config/keys');

const User = mongoose.model('users');

// Take the ID of a user for Passport to put into a cookie
passport.serializeUser((user, done) => {
  done(null, user.id); // user.id is the record ID automatically generated by Mongo (NOT the profile.id)
});

// Take the ID in a cookie and find which user in MongoDB it is referencing
passport.deserializeUser((id, done) => {
  User.findById(id)
    .then(user => {
      done(null, user);
    });
});

// passport.use() function parameters explained
// Parameter 1: the strategy to be used by Passport.js
//             - takes an object with client ID, secret and a callback URL
// Parameter 2: the callback function executed when the authentication flow is completed successfully
//      takes: - an accessToken (the code in the URL returned by the OAuth) - allows access to requested information specified in scope
//             - a refreshToken allows the accessToken (which expires) to be updated for accessing again
//             - the data requested, to demonstrate successful access
//             - done function that is defined by passport to finalise the strategy. This requires two parameters
//               > an error object (null if successful)
//               > the user that we just tried to authenticate through Google

passport.use(new GoogleStrategy({
    clientID: keys.GOOGLE_CLIENT_ID,
    clientSecret: keys.GOOGLE_CLIENT_SECRET,
    callbackURL: '/auth/google/callback',
    proxy: true
  }, (accessToken, refreshToken, profile, done) => {
    User.findOne({ googleID: profile.id })
      .then((existingUser) => { // JS promise - to handle asynchronous requests
        if(existingUser) {
          console.log('\nUser already exists. ' + profile.name.givenName + ' is logged in!\n');
          done(null, existingUser);
        } else {
          new User({ googleID: profile.id })
            .save()
            .then(user => {
              console.log('\nNew user created! ' + profile.name.givenName + ' is logged in!\n');
              done(null, user);
            });
        }
      });
  })
);
